# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AsyncronousTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AsyncronousTest

  target 'AsyncronousTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AsyncronousTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  pod 'PromiseKit'
  pod 'Bolts-Swift'
  
  pod 'RxSwift'

end
