# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AsynchronousBasicTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AsynchronousBasicTest

  target 'AsynchronousBasicTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AsynchronousBasicTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'RxSwift'

end
