# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwiftSubjectTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSwiftSubjectTest

  target 'RxSwiftSubjectTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxSwiftSubjectTestUITests' do
    # Pods for testing
  end
  pod 'RxSwift'  

end
