# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ObservableTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ObservableTest

  target 'ObservableTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ObservableTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'RxSwift'

end
